---
title: "Act 1.3"
output:
  word_document: default
  html_notebook: default
---

```{r}
print("De un grupo de 5 estudiantes de IDM, 7 de IFI y 6 de INA se desea formar un comité de
6 personas.
a) Si se desea que el comité consista de 2 estudiantes de cada carrera, ¿Cuántos comités
se pueden formar?
b) Si no hay restricciones para el comité, ¿Cuál es la probabilidad de que en el comité
haya exactamente 4 estudiantes de IFI?
c) Si no hay restricciones, ¿Cuál es la probabilidad de que en el comité haya al menos
un estudiante de IDM y uno de INA?")

#a) 

comités <- choose(5,2) * choose(7,2) * choose(6,2)
cat("\ncomités que se pueden formar:",comités)

#b) 
universo <- choose(18,6)
favorables <- choose(7,4) * choose(11,2)
prob <- favorables / universo
cat("\n\nprobabilidad de que en el comité haya exactamente 4 estudiantes de IFI:",prob)

#c) 
total <- choose(18,6)
sin_IDM <- choose(13,6)
sin_INA <- choose(12,6)
sin_ambos <- choose(7,6)

prob <- 1 - (sin_IDM + sin_INA - sin_ambos) / total
cat("\n\nprobabilidad de que en el comité haya al menos un estudiante de IDM y uno de INA:",prob)
```
```{r}
print("¿Cuántos conjuntos de cuatro letras se pueden formar de un conjunto de 10 letras diferentes si no hay restricciones excepto que ninguna letra puede usarse más de una vez?")

conjuntos <- choose(10,4)
cat("\n\nconjuntos de cuatro letras se pueden formar de un conjunto de 10 letras diferentes si no hay restricciones excepto que ninguna letra puede usarse más de una vez:",conjuntos)

```
```{r}
print("Una agencia automotriz que recibió un lote 14 autos de un determinado modelo de vehículo en el fin de semana pasado, hizo entrega de 7 de éstos a sus clientes. Hoy la planta de manufactura reporta haber incluido en el ensamble de 3 de estos un dispositivo de frenos ABS defectuoso. ¿Cuál es la probabilidad de que todos los autos vendidos estén libres de problemas con el ABS?")

universo <- choose(14,7)
no_def <- choose(11,7)
prob <- no_def/universo
cat("\n\nprobabilidad de que todos los autos vendidos estén libres de problemas con el ABS:",prob)

```
```{r}
print("Con los números 2, 2, 2, 3, 3, 3, 3, 4, 4, ¿Cuántos números diferentes de 9 cifras se pueden formar?")

comb <- (factorial(9))/(factorial(3)*factorial(4)*factorial(2))
cat("\n\nnúmeros diferentes de 9 cifras se pueden formar:",comb)
```




