---
title: "Etapa 2 gráficas (J)"
output: html_notebook
---
#Gráficas de libros leidos y tiempo seccionados 

```{r}
library(tidyverse)
library(here)

Mfinal = read.csv("DATA.csv")

```

#Vamos a hacer las gráficas de tiempo leido vs libros leidos y los vamos a segmentar en nivel educativo y trabajo para ver si esto hace una diferencia en lo que una persona lee. (con esto podemos evitarnos hacer as desviaciones estandars de los datos que queremos segmentar)



#Nivel educativo
```{r}
ggplot(Mfinal, aes(x=p26, y=material_leido,color=as.factor(nivel)))+ geom_point(size=3) +  scale_color_brewer(palette = "Set1")+ labs(title="Libros leídos V.S. tiempo que lee continuamente", subtitle="Segmentado por nivel educativo", x="Tiempo que lee continuamente",y="Material leido", color="Nivel educativo")+ theme_minimal()
```

#Trabajo 
```{r}
ggplot(Mfinal, aes(x=p26, y=material_leido,color=as.factor(cond_act)))+ geom_point(size=3, ) +  scale_color_brewer(palette = "Set1")  + labs(title="Libros leídos V.S. tiempo que lee continuamente", subtitle="Segmentado por actividad que desempeña", x="Tiempo que lee continuamente",y="Material leido", color="Actividad que desempeña")+ theme_minimal()
```

